### ISSUE TITLE
Can't figure out how to use everyPlayer - maybe it's broken?

### ISSUE THREAD

**Issue by mvolfik** [boardzilla/boardzilla-core#15]
Hi, I'm exploring this project and it seems like a promising framework, great job!

I'm struggling when trying to use `everyPlayer`. Here's a simple reproduction that I put together: I used the _Simple game_ template from @boardzilla/create-game, with just a simple modification: instead of creating one central pool, I created a separate pool for each player, to prevent race conditions. [Full diff here](https://github.com/mvolfik/boardzilla-everyPlayer-repro/commit/386982c55306abe146f60d34df69eb94a1c576c0), if you `npm install && npm run dev` you get a full reproduction of my issue.

Everything works correctly with `eachPlayer`, but when I substitute it for `everyPlayer`, the game simply breaks: when I select a token, there isn't any state added in the devtools sidebar, and in console I get `move may no longer be valid. retrying getPendingMoves `.

Am I using this wrong, or is there some bug? Thanks

**Comment by aghull** [comment]
Corrected in https://github.com/boardzilla/boardzilla-core/pull/13
